apiVersion: v1
kind: Service
metadata:
  name: java-webapp
  labels:
    app: java-webapp
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: java-webapp
    tier: java-webapp
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: java-webapp
  labels:
    app: java-webapp
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: java-webapp
        tier: java-webapp
    spec:
      containers:
      - image: 127.0.0.1:30400/java-webapp:version
        name: java-webapp
        ports:
        - containerPort: 80
          name: java-webapp
