apiVersion: v1
kind: Service
metadata:
  name: jetty-alpine
  labels:
    app: jetty-alpine
spec:
  ports:
    - port: 8080
  selector:
    app: jetty-alpine
    tier: jetty-alpine
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jetty-alpine
  labels:
    app: jetty-alpine
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jetty-alpine
        tier: jetty-alpine
    spec:
      containers:
      - image: 127.0.0.1:30400/jetty-alpine:version
        name: jetty-alpine
        ports:
        - containerPort: 8080
          name: jetty-alpine
