apiVersion: v1
kind: Service
metadata:
  name: rest-java-jetty
  labels:
    app: rest-java-jetty
spec:
  ports:
    - port: 8080
  selector:
    app: rest-java-jetty
    tier: rest-java-jetty
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rest-java-jetty
  labels:
    app: rest-java-jetty
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rest-java-jetty
        tier: rest-java-jetty
    spec:
      containers:
      - image: 127.0.0.1:30400/rest-java-jetty:version
        name: rest-java-jetty
        ports:
        - containerPort: 8080
          name: rest-java-jetty
